kind: pipeline
name: dev
type: kubernetes
dns_config:
  options:
    - name: ndots
      value: '1'
steps:
  - name: build
    image: plugins/kaniko
    settings:
      username: k3env
      password:
        from_secret: DOCKER_PASSWORD
      repo: ${DRONE_REPO}
      dockerfile: Dockerfile
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
  - name: deploy
    image: ghcr.io/bh90210/dron8s:latest
    settings:
      yaml: .ci/deployment.yaml
      tag: ${DRONE_COMMIT_SHA:0:8}
      ns: landing-dev
  - name: send notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: TG_TOKEN
      to:
        from_secret: TG_CHANNEL
      message_file: .ci/build-message.tg.tpl
    when:
      status:
        - success
        - failure
trigger:
  event:
    - push
---
kind: pipeline
name: release
type: kubernetes
dns_config:
  options:
    - name: ndots
      value: '1'
steps:
  - name: build
    image: plugins/kaniko
    settings:
      username: k3env
      password:
        from_secret: DOCKER_PASSWORD
      repo: ${DRONE_REPO}
      tags:
        - ${DRONE_TAG}
        - stable
        - latest
  - name: deploy
    image: ghcr.io/bh90210/dron8s:latest
    settings:
      yaml: .ci/deployment.yaml
      tag: ${DRONE_TAG}
      ns: landing
  - name: send notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: TG_TOKEN
      to:
        from_secret: TG_CHANNEL
      message_file: .ci/build-message.tg.tpl
    when:
      status:
        - success
        - failure
trigger:
  event:
    - tag
