apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-next
  namespace: personal
spec:
  selector:
    matchLabels:
      app: api-next
  template:
    metadata:
      labels:
        app: api-next
    spec:
      containers:
        - name: api
          image: k3env/landing-cv-api-next:latest
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 3000
