apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: '{{.ns}}'
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: static-volume
      containers:
        - name: api
          image: k3env/landing-cv-api-next:{{.tag}}
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          envFrom:
            - configMapRef:
                name: api-env
          volumeMounts:
            - mountPath: /app/public
              name: static
          ports:
            - containerPort: 3000
